import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToggleContextProvider from '@/context/useModal'
import { CreateUserProvider } from '@/context/useForms'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToggleContextProvider>
                    <CreateUserProvider>{children}</CreateUserProvider>
                </ToggleContextProvider>
            </body>
        </html>
    )
}
